# Generated by Django 5.0.3 on 2024-04-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_AVION', models.IntegerField()),
                ('S_N', models.CharField(max_length=13)),
                ('DATE_DE_POSE', models.CharField(max_length=10)),
                ('DATE_POCHAINE_RG', models.CharField(max_length=10)),
                ('OBS', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='liaisonavionpiece',
            name='avion',
        ),
        migrations.RemoveField(
            model_name='liaisonavionpiece',
            name='piece',
        ),
        migrations.DeleteModel(
            name='Avion',
        ),
        migrations.DeleteModel(
            name='LiaisonAvionPiece',
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
    ]
