# Generated by Django 5.0.3 on 2024-04-17 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book2_remove_liaisonavionpiece_avion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_avion', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceHeure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.CharField(max_length=10)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.avion')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Book2',
        ),
        migrations.AddField(
            model_name='maintenanceheure',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.maintenanceoperation'),
        ),
    ]
