# Generated by Django 5.0.3 on 2024-04-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_avion_maintenanceheure_maintenanceoperation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceheure',
            name='heure',
            field=models.CharField(max_length=100),
        ),
    ]
