# Generated by Django 5.0.3 on 2024-04-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_maintenanceheure_date_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceheure',
            name='heure',
            field=models.DateTimeField(),
        ),
    ]
