# Generated by Django 5.0.3 on 2024-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_organes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organes',
            name='accu_vol_dos_5ans',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organes',
            name='helice_5ans',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organes',
            name='reg_helice_5ans',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
