# Generated by Django 5.0.3 on 2024-04-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_organes_accu_vol_dos_5ans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceheure',
            name='heures_vol',
            field=models.IntegerField(default=0),
        ),
    ]
