# Generated by Django 5.0.3 on 2024-04-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_avion_heures_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='heure',
            field=models.CharField(default='', max_length=255),
        ),
    ]
