# Generated by Django 5.0.3 on 2024-04-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_avion_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avion',
            name='heure',
            field=models.CharField(default='00:00', max_length=255),
        ),
    ]
