# Generated by Django 5.0.3 on 2024-05-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_avion_heure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('support', models.CharField(max_length=100)),
            ],
        ),
    ]
