# Generated by Django 5.0.3 on 2024-05-02 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='myapp.avion')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='myapp.material')),
            ],
        ),
    ]
