# Generated by Django 5.0.3 on 2024-05-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_besoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organes',
            name='Moteur_12ans',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
