# Generated by Django 5.0.3 on 2024-05-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_organes_moteur_12ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='organes',
            name='heure',
            field=models.CharField(default='00:00', max_length=255),
        ),
    ]
