# Generated by Django 5.0.3 on 2024-05-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_organes_heure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('Organes', 'Organes'), ('Operations', 'Operations')], max_length=50)),
                ('count_type', models.IntegerField(default=1)),
            ],
        ),
    ]
