# Generated by Django 5.0.3 on 2024-05-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_organes_moteur_12ans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organes',
            name='avion',
        ),
        migrations.RemoveField(
            model_name='organes',
            name='heures_vol',
        ),
        migrations.RemoveField(
            model_name='organes',
            name='operation',
        ),
        migrations.AddField(
            model_name='organes',
            name='Moteur_12ans',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organes',
            name='accu_vol_dos_5ans',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organes',
            name='fuel_injecter_1600h',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organes',
            name='fuel_pump_2000h',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organes',
            name='hdf_actuel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organes',
            name='helice_5ans',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organes',
            name='magnetos_D_2000h',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organes',
            name='magnetos_G_2000h',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organes',
            name='numero_avion',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organes',
            name='reg_helice_5ans',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organes',
            name='heure',
            field=models.CharField(default='00:00', max_length=255),
        ),
    ]
