# Generated by Django 5.0.3 on 2024-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_parachute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('pn', models.CharField(max_length=100)),
                ('limite_calendaire', models.CharField(max_length=100)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
