# Generated by Django 5.0.3 on 2024-05-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_piece'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('avionne_ste', models.CharField(max_length=100)),
                ('basg', models.CharField(max_length=100)),
                ('dispo_unite', models.CharField(choices=[('X', 'X'), ('', '')], max_length=1)),
                ('indispo_unite', models.CharField(choices=[('X', 'X'), ('', '')], max_length=1)),
            ],
        ),
    ]
