# Generated by Django 5.0.3 on 2024-05-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_materiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='avionne_ste',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='position',
        ),
        migrations.AddField(
            model_name='materiel',
            name='Serial_number',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='materiel',
            name='avionnee',
            field=models.CharField(choices=[('X', 'X'), ('', '')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='materiel',
            name='ste',
            field=models.CharField(choices=[('X', 'X'), ('', '')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='basg',
            field=models.CharField(choices=[('X', 'X'), ('', '')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='designation',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='dispo_unite',
            field=models.CharField(choices=[('X', 'X'), ('', '')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='indispo_unite',
            field=models.CharField(choices=[('X', 'X'), ('', '')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='part_number',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
