# Generated by Django 5.0.3 on 2024-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_materiel_avionne_ste_remove_materiel_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='Serial_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='avionnee',
            field=models.CharField(blank=True, choices=[('X', 'X'), ('', '')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='basg',
            field=models.CharField(blank=True, choices=[('X', 'X'), ('', '')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='dispo_unite',
            field=models.CharField(blank=True, choices=[('X', 'X'), ('', '')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='indispo_unite',
            field=models.CharField(blank=True, choices=[('X', 'X'), ('', '')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='part_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='ste',
            field=models.CharField(blank=True, choices=[('X', 'X'), ('', '')], default='', max_length=1),
        ),
    ]
