# Generated by Django 5.0.3 on 2024-05-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_materiel_serial_number_alter_materiel_avionnee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('av_number', models.CharField(max_length=10)),
                ('engine_number', models.CharField(max_length=20)),
                ('tso', models.CharField(max_length=20)),
                ('tsn', models.CharField(max_length=20)),
                ('next_rg_date', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True)),
            ],
        ),
    ]
